---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: systest
  name: chrome
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: chrome
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: chrome
    spec:
      securityContext:
        runAsUser: 1200
        runAsGroup: 1201
        fsGroup: 1201
      containers:
        - image: selenium/standalone-chrome:4.0.0
          imagePullPolicy: Always
          name: chrome
          ports:
            - containerPort: 4444
          volumeMounts:
            - name: downloads
              mountPath: /home/seluser/Downloads
          env:
          - name: MAX_PARALLEL_PROCESS_COUNT
            value: "1"
          - name: TSM_VERIFICATION_SERVICE_CONFIG_FILE
            value: " "
          - name: IMG_PREPROC_TIMEOUT
            value: "10m"
          - name: IMG_PREPROC_PER_PAGE_TIMEOUT
            value: "2m"
          - name: TSM_USE_IMAGE_PREPROCESSING
            value: "derotation_and_deskew_and_improve"
          - name: DATA_CURATION_MODE
            value: " "
      volumes:
        - name: downloads
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  namespace: systest
  name: chrome
spec:
  ports:
    - port: 4444
      targetPort: 4444
      protocol: TCP
  selector:
    app.kubernetes.io/name: chrome

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: systest
  name: browsermob-proxy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: browsermob-proxy
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: browsermob-proxy
    spec:
      containers:
        - image: bwowk/browsermob-proxy
          imagePullPolicy: Always
          name: browsermob-proxy
          ports:
            - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  namespace: systest
  name: browsermob-proxy
spec:
  ports:
    - port: 8080
      targetPort: 8888
      protocol: TCP
  selector:
    app.kubernetes.io/name: browsermob-proxy
